### ISSUE TITLE
Very old :(

### ISSUE THREAD

**Issue by Tenshi147** [HausemasterIssue/Opfern-Decomp#2]
Sup, so 1.3.0Beta is probably one of the oldest leaked jars of Opfern (I'd say over a year and a half or more, 1.5.2 dropped in January of 2021 soooo) I highly doubt it still performs at all on constantiam because it had to have a CA rewrite in the 1.5.4 update due to its lack of performance

**Comment by HausemasterIssue** [comment]
Oh ok, so my guess of mid 2020 was pretty close. This client is basically all shit, but the surround is absolutely insane. It performs very well, almost as good as Futures. Could you send the 1.5.2 version jar over mediafire please? I'd like to how the client improved.

**Comment by master7720** [comment]
@HausemasterIssue i may have 1.5.2 so when i get home i will see if i can find it :0

**Comment by Tenshi147** [comment]
If it's any of the beta versions then that's pre CA rewrite

**Comment by master7720** [comment]
> If it's any of the beta versions then that's pre CA rewrite

Can you just send a media fire for the jar?

**Comment by HausemasterIssue** [comment]
^

**Comment by master7720** [comment]
https://www.mediafire.com/file/neuurx3cdy7prgh/1.5.1_beta.jar/file theres the newest version i have

**Comment by master7720** [comment]
@HausemasterIssue say thank you

**Comment by HausemasterIssue** [comment]
Thank you master 🙄

**Comment by master7720** [comment]
> Thank you master 🙄

:)

**Comment by master7720** [comment]
@Tenshi147 u should open source opfern ngl even tho its old would be cool to look at
